server:
  port: 9001

spring:

  jackson:
    default-property-inclusion: non_null

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.133:3306/paulson?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: mima

  jpa:
    hibernate:
      ddl-auto: update  # 更改表结构
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: 192.168.2.133
    port: 6379

  profiles:
    active: dev
#
#logging:
#  level:
#    org.springframework.security:
#      - debug
#      - info
#    org.springframework.web: error
#    org.hibernate.SQL: debug
#    org.hibernate.engine.QueryParameters: debug
#    org.hibernate.engine.query.HQLQueryPlan: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace

#config: classpath:logback-spring.xml